// auto-generated by genOpcodes.ts

/**
 * Instruction argument types.
 */
export const ArgType = {
    /** Unsigned 8-bit value */
    UInt8: 0,
    /** Unsigned 8-bit register index */
    Reg8: 1,
    /** Signed 8-bit relative address */
    Addr8: 2,
    /** Unsigned 16-bit value */
    UInt16: 3,
    /** Unsigned 32-bit value */
    UInt32: 4,
    /** Unsigned 32-bit register index */
    Reg32: 5,
    /** Signed 32-bit immediate */
    Imm32: 6,
    /** Signed 32-bit relative address */
    Addr32: 7,
    /** Double-precision floating point number */
    Double: 8,
} as const;

export type ArgType = typeof ArgType[keyof typeof ArgType];

/**
 * Numeric Hermes instruction opcodes.
 */
export const Opcode = {
    /**
     * Unreachable opcode for stubs and similar. This is first so that it has the
     * value zero.
     */
    Unreachable: 0,
    /**
     * Create an object from a static map of values, as for var={'a': 3}.
     * Any non-constant elements can be set afterwards with PutOwnByInd.
     * Arg1 is the destination.
     * Arg2 is the index in the object shape table.
     * Arg3 is the index in the object val buffer table.
     */
    NewObjectWithBuffer: 1,
    NewObjectWithBufferLong: 2,
    /**
     * Create an object from a static map of values, setting its parent.
     * Arg1 is the destination.
     * Arg2 is the parent.
     * Arg3 is the index in the object shape table.
     * Arg4 is the index in the object val buffer table.
     */
    NewObjectWithBufferAndParent: 3,
    /**
     * Create a new, empty Object using the built-in constructor (regardless of
     * whether it was overridden).
     * Arg1 = {}
     */
    NewObject: 4,
    /**
     * Create a new empty Object with the specified parent. If the parent is
     * null, no parent is used. If the parent is not an object, the builtin
     * Object.prototype is used. Otherwise the parent itself is used.
     * Arg1 = the created object
     * Arg2 = the parent.
     */
    NewObjectWithParent: 5,
    /**
     * Create an array from a static list of values, as for var=[1,2,3].
     * Any non-constant elements can be set afterwards with DefineOwnByIndex.
     * Arg1 is the destination.
     * Arg2 is a preallocation size hint.
     * Arg3 is the number of static elements.
     * Arg4 is the index in the array buffer table.
     */
    NewArrayWithBuffer: 6,
    NewArrayWithBufferLong: 7,
    /**
     * Create a new array of a given size.
     * Arg1 = new Array(Arg2)
     */
    NewArray: 8,
    /**
     * Create a new FastArray.
     * Arg1 = new FastArray(Arg2)
     */
    NewFastArray: 9,
    /**
     * Get the length of a FastArray.
     * Arg1 = Arg2.length
     */
    FastArrayLength: 10,
    /**
     * Load from a FastArray.
     * Arg1 = Arg2[Arg3]
     */
    FastArrayLoad: 11,
    /**
     * Store to a FastArray.
     * Arg1[Arg2] = Arg3
     */
    FastArrayStore: 12,
    /**
     * Push an element onto the end of a FastArray.
     * Arg1.push(Arg2)
     */
    FastArrayPush: 13,
    /**
     * Append a FastArray onto another FastArray.
     * Arg1.append(Arg2)
     */
    FastArrayAppend: 14,
    /**
     * Perform a lookup on the new object cache.
     * Arg1 = the 'this' value to lookup
     * Arg2 = the new target to determine whether it is a constructor call
     * Arg3 = the index in the shape table.
     * Arg4 = the cache index within the current function
     */
    CacheNewObject: 15,
    /**
     * Arg1 = Arg2 (Register copy)
     */
    Mov: 16,
    /**
     * Arg1 = Arg2 (Register copy, long index)
     */
    MovLong: 17,
    /**
     * Arg1 = -Arg2 (Unary minus)
     */
    Negate: 18,
    /**
     * Arg1 = !Arg2 (Boolean not)
     */
    Not: 19,
    /**
     * Arg1 = ~Arg2 (Bitwise not)
     */
    BitNot: 20,
    /**
     * Arg1 = typeof Arg2 (JS typeof)
     */
    TypeOf: 21,
    /**
     * Arg1 = Arg2 == Arg3 (JS equality)
     */
    Eq: 22,
    /**
     * Arg1 = Arg2 === Arg3 (JS strict equality)
     */
    StrictEq: 23,
    /**
     * Arg1 = Arg2 != Arg3 (JS inequality)
     */
    Neq: 24,
    /**
     * Arg1 = Arg2 !== Arg3 (JS strict inequality)
     */
    StrictNeq: 25,
    /**
     * Arg1 = Arg2 < Arg3 (JS less-than)
     */
    Less: 26,
    /**
     * Arg1 = Arg2 <= Arg3 (JS less-than-or-equals)
     */
    LessEq: 27,
    /**
     * Arg1 = Arg2 > Arg3 (JS greater-than)
     */
    Greater: 28,
    /**
     * Arg1 = Arg2 >= Arg3 (JS greater-than-or-equals)
     */
    GreaterEq: 29,
    /**
     * Arg1 = Arg2 + Arg3 (JS addition/concatenation)
     */
    Add: 30,
    /**
     * Arg1 = Arg2 + Arg3 (Numeric addition, skips number check)
     */
    AddN: 31,
    /**
     * Arg1 = Arg2 + Arg3 (String concat, skips string check)
     */
    AddS: 32,
    /**
     * Arg1 = Arg2 * Arg3 (JS multiplication)
     */
    Mul: 33,
    /**
     * Arg1 = Arg2 * Arg3 (Numeric multiplication, skips number check)
     */
    MulN: 34,
    /**
     * Arg1 = Arg2 / Arg3 (JS division)
     */
    Div: 35,
    /**
     * Arg1 = Arg2 / Arg3 (Numeric division, skips number check)
     */
    DivN: 36,
    /**
     * Arg1 = Arg2 % Arg3 (JS remainder)
     */
    Mod: 37,
    /**
     * Arg1 = Arg2 - Arg3 (JS subtraction)
     */
    Sub: 38,
    /**
     * Arg1 = Arg2 - Arg3 (Numeric subtraction, skips number check)
     */
    SubN: 39,
    /**
     * Arg1 = Arg2 << Arg3 (JS bitshift left)
     */
    LShift: 40,
    /**
     * Arg1 = Arg2 >> Arg3 (JS signed bitshift right)
     */
    RShift: 41,
    /**
     * Arg1 = Arg2 >>> Arg3 (JS unsigned bitshift right)
     */
    URshift: 42,
    /**
     * Arg1 = Arg2 & Arg3 (JS bitwise AND)
     */
    BitAnd: 43,
    /**
     * Arg1 = Arg2 ^ Arg3 (JS bitwise XOR)
     */
    BitXor: 44,
    /**
     * Arg1 = Arg2 | Arg3 (JS bitwise OR)
     */
    BitOr: 45,
    /**
     * Arg1 = Arg2 + 1 (JS increment, skips number check)
     */
    Inc: 46,
    /**
     * Arg1 = Arg2 - 1 (JS decrement, skips number check)
     */
    Dec: 47,
    /**
     * Check whether Arg2 contains Arg3 in its prototype chain.
     * Note that this is not the same as JS instanceof.
     * Pseudocode: Arg1 = prototypechain(Arg2).contains(Arg3)
     */
    InstanceOf: 48,
    /**
     * Arg1 = Arg2 in Arg3 (JS relational 'in')
     */
    IsIn: 49,
    /**
     * Arg1 = Arg2 in Arg3 (JS relational 'in' for private names.)
     * Arg2 must be a symbol.
     * Arg4 is a private name cache index used to speed up the above operation.
     * Note that this performs different logic than a normal `in` check. This
     * instruction does not consult the prototype chain or trigger any proxy
     * traps. It is a direct check on the own properties of the input object.
     */
    PrivateIsIn: 50,
    /**
     * Arg1 = typeof Arg2 is in Arg3 (TypeOfIsTypes, see Typeof.h)
     */
    TypeOfIs: 51,
    /**
     * Get an environment (scope) from N levels up relative to the current
     * function's enclosing environment. 0 retrieves the environment from the
     * closure, 1 retrieves its parent, etc.
     */
    GetParentEnvironment: 52,
    /**
     * Get an environment by traversing the scope chain.
     * Arg1 is the destination.
     * Arg2 is the environment from which to start traversing.
     * Arg3 is the number of levels up the scope chain to go.
     */
    GetEnvironment: 53,
    /**
     * Get the environment from a closure.
     * Arg1 is the destination.
     * Arg2 is the closure from which to read.
     */
    GetClosureEnvironment: 54,
    /**
     * Store a value in an environment.
     * StoreNPToEnvironment[L] store a non-pointer value in an environment
     * Arg1 is the environment (as fetched by GetEnvironment).
     * Arg2 is the environment index slot number.
     * Arg3 is the value.
     */
    StoreToEnvironment: 55,
    StoreToEnvironmentL: 56,
    StoreNPToEnvironment: 57,
    StoreNPToEnvironmentL: 58,
    /**
     * Load a value from an environment.
     * Arg1 is the destination.
     * Arg2 is the environment (as fetched by GetEnvironment).
     * Arg3 is the environment index slot number.
     */
    LoadFromEnvironment: 59,
    LoadFromEnvironmentL: 60,
    /**
     * Get the global object (the object in which global variables are stored).
     */
    GetGlobalObject: 61,
    /**
     * Obtain the value of NewTarget from the frame.
     * Arg1 = NewTarget
     */
    GetNewTarget: 62,
    /**
     * Get the parent of a given object. The parent will either be an object or null.
     * Arg1 = destination register to write the parent.
     * Arg2 = the object.
     */
    LoadParentNoTraps: 63,
    /**
     * Create a new environment, using the current function's enclosing environment
     * as the parent.
     * Arg1 is the destination.
     * Arg2 is the size of the new environment.
     */
    CreateFunctionEnvironment: 64,
    /**
     * Create a top level environment, without a parent.
     * TODO: Consider removing this in favor of using CreateEnvironment by using a
     *       different scheme for encoding the top level environment.
     * Arg1 is the destination.
     * Arg2 is the size of the new environment.
     */
    CreateTopLevelEnvironment: 65,
    /**
     * Create a new environment with the given parent.
     * Arg1 is the destination.
     * Arg2 is the parent environment to use.
     * Arg3 is the size of the new environment.
     */
    CreateEnvironment: 66,
    /**
     * Declare a global variable by string table index.
     * The variable will be set to undefined.
     */
    DeclareGlobalVar: 67,
    /**
     * Get an object property by string table index.
     * Arg1 = Arg2[stringtable[Arg4]]
     * Arg3 is a cache index used to speed up the above operation.
     */
    GetByIdShort: 68,
    GetById: 69,
    GetByIdLong: 70,
    /**
     * Get an object property by string table index, with a specified receiver.
     * Arg1 = Arg2[stringtable[Arg5]]
     * Arg1 is the destination.
     * Arg2 is the object to begin the property look up.
     * Arg3 is a cache index used to speed up the above operation.
     * Arg4 is receiver.
     * Arg5 is the string id.
     */
    GetByIdWithReceiverLong: 71,
    /**
     * Get an object property by string table index, or throw if not found.
     * This is similar to GetById, but intended for use with global variables
     * where Arg2 = GetGlobalObject.
     */
    TryGetById: 72,
    TryGetByIdLong: 73,
    /**
     * Set an object property by string index.
     * Arg1[stringtable[Arg4]] = Arg2.
     */
    PutByIdLoose: 74,
    PutByIdStrict: 75,
    PutByIdLooseLong: 76,
    PutByIdStrictLong: 77,
    /**
     * Set an object property by string index, or throw if undeclared.
     * This is similar to PutById, but intended for use with global variables
     * where Arg1 = GetGlobalObject.
     */
    TryPutByIdLoose: 78,
    TryPutByIdStrict: 79,
    TryPutByIdLooseLong: 80,
    TryPutByIdStrictLong: 81,
    /**
     * Set an existing own property identified at a slot index.
     * Arg1 is the destination object.
     * Arg2 is the value to write.
     * Arg3 is the hidden class slot index.
     * Arg1[Arg3] = Arg2;
     */
    PutOwnBySlotIdx: 82,
    PutOwnBySlotIdxLong: 83,
    /**
     * Get an existing own property at a given slot index.
     * Arg1 is the result register.
     * Arg2 is the object.
     * Arg3 is the hidden class slot index.
     * Arg2[Arg3] = Arg2;
     */
    GetOwnBySlotIdx: 84,
    GetOwnBySlotIdxLong: 85,
    /**
     * Define an object own property by string index.
     * Arg1[stringtable[Arg4]] = Arg2.
     * Arg3 is a cache index.
     */
    DefineOwnById: 86,
    DefineOwnByIdLong: 87,
    /**
     * Assign a value to a constant integer own property which will be created as
     * enumerable. This is used (potentially in conjunction with
     * NewArrayWithBuffer) for arr=[foo,bar] initializations.
     * Arg1[Arg3] = Arg2;
     */
    DefineOwnByIndex: 88,
    DefineOwnByIndexL: 89,
    /**
     * Define an own property in a dense JavaScript array at a specific index.
     * Requires that the array is dense and that the ArrayStorage
     * underlying it has a size which is greater than the arrayIndex operand.
     * Arg1[Arg3] = Arg2;
     * Arg1 is the dense array object where the property will be defined.
     * Arg2 is the value to be stored.
     * Arg3 is the array index where the property will be stored.
     * NOTE: The "L" version only goes up to 16-bit array indices,
     * because NewArray only takes UInt16 argument.
     */
    DefineOwnInDenseArray: 90,
    DefineOwnInDenseArrayL: 91,
    /**
     * Set an own property identified by value.
     * Arg1 is the destination object.
     * Arg2 is the value to write.
     * Arg3 is the property name.
     * Arg4 : bool -> enumerable. If true, the property is created as enumerable,
     *        non-enumerable otherwise.
     * Arg1[Arg3] = Arg2;
     */
    DefineOwnByVal: 92,
    /**
     * Get a property by value. Constants string values should instead use GetById.
     * Arg1 = Arg2[Arg3]
     */
    GetByVal: 93,
    /**
     * Get a property by value, for the special case where the property is a
     * numeric literal that is a uint8_t integer. Arg1 = Arg2[Arg3]
     */
    GetByIndex: 94,
    /**
     * Get a property by value with a specified receiver.
     * Arg1 = Arg2[Arg3]
     * Arg1 is the destination register.
     * Arg2 is the object to begin the property look up. It must be an object.
     * Arg3 is the property key.
     * Arg4 is the receiver.
     */
    GetByValWithReceiver: 95,
    /**
     * Set a property by value. Constant string values should instead use GetById
     * (unless they are array indices according to ES5.1 section 15.4, in which
     * case this is still the right opcode).
     * Arg1[Arg2] = Arg3
     */
    PutByValLoose: 96,
    PutByValStrict: 97,
    /**
     * Set a property by value, with a specified receiver.
     * Arg1[Arg2] = Arg3
     * Arg4 is the receiver
     * Arg5 is true if this operation is strict, false for loose.
     */
    PutByValWithReceiver: 98,
    /**
     * Delete a property by value (when the value is not known at compile time).
     * Arg1 = delete Arg2[Arg3]
     * Arg4 : Integer value set to 1 for strict mode semantics, 0 for loose.
     */
    DelByVal: 99,
    /**
     * Add a private property to an object. This must be a new property.
     * The property will be added with the privateName flag set on the PropertyFlags.
     * Arg1[Arg2] = Arg3
     */
    AddOwnPrivateBySym: 100,
    /**
     * Get a private property from an object.
     * Arg1 = Arg2[Arg5]
     * Arg1 is the result
     * Arg2 is the object to read from.
     * Arg3 is a private name cache index used to speed up the above operation.
     * Arg4 is the symbol value of the private name.
     */
    GetOwnPrivateBySym: 101,
    /**
     * Store a private property to an object.
     * Arg1[Arg5] = Arg2
     * Arg1 is the object to store to.
     * Arg2 is the value to store.
     * Arg3 is a private name cache index used to speed up the above operation.
     * Arg4 is the symbol value of the private name.
     */
    PutOwnPrivateBySym: 102,
    /**
     * Add a getter and a setter for a property by value.
     * Object.defineProperty(Arg1, Arg2, { get: Arg3, set: Arg4 }).
     * Arg1 is the target object which will have a property defined.
     * Arg2 is the property name
     * Arg3 is the getter closure or undefined
     * Arg4 is the setter closure or undefined
     * Arg5 : boolean - if true, the property will be enumerable.
     */
    DefineOwnGetterSetterByVal: 103,
    /**
     * Get the list of properties from an object to implement for..in loop.
     * Returns Arg1, which is the register that holds array of properties.
     * Returns Undefined if the object is null/undefined.
     * Arg2 is the register that holds the object.
     * Arg3 is the register that holds the iterating index.
     * Arg4 is the register that holds the size of the property list.
     */
    GetPNameList: 104,
    /**
     * Get the next property in the for..in iterator.
     * Returns Arg1, which is the next property. Undefined if unavailable.
     * Arg2 is the register that holds array of properties.
     * Arg3 is the register that holds the object.
     * Arg4 is the register that holds the iterating index.
     * Arg5 is the register that holds the size of the property list.
     */
    GetNextPName: 105,
    /**
     * Call a function.
     * Arg1 is the destination of the return value.
     * Arg2 is the closure to invoke.
     * Arg3 is the number of arguments, assumed to be found in reverse order
     *      from the end of the current frame.
     */
    Call: 106,
    /**
     * Call a constructor, with semantics identical to Call.
     * Arg1 is the destination of the return value.
     * Arg2 is the closure to invoke.
     * Arg3 is the number of arguments, assumed to be found in reverse order
     *      from the end of the current frame. The first argument 'this'
     *      is assumed to be created with CreateThis.
     */
    Construct: 107,
    /**
     * Call a function with one arg.
     * Arg1 is the destination of the return value.
     * Arg2 is the closure to invoke.
     * Arg3 is the first argument.
     */
    Call1: 108,
    /**
     * Call a function with an explicitly specified `new.target`.
     * Arg1 is the destination of the return value.
     * Arg2 is the closure to invoke.
     * Arg3 is the value of new.target
     * Arg4 is the number of arguments, assumed to be found in reverse order
     *      from the end of the current frame.
     */
    CallWithNewTarget: 109,
    /**
     * Call a function with two args.
     * Arg1 is the destination of the return value.
     * Arg2 is the closure to invoke.
     * Arg3 is the first argument.
     * Arg4 is the second argument.
     */
    Call2: 110,
    /**
     * Call a function with three args.
     * Arg1 is the destination of the return value.
     * Arg2 is the closure to invoke.
     * Arg3 is the first argument.
     * Arg4 is the second argument.
     * Arg5 is the third argument.
     */
    Call3: 111,
    /**
     * Call a function with four args.
     * Arg1 is the destination of the return value.
     * Arg2 is the closure to invoke.
     * Arg3 is the first argument.
     * Arg4 is the second argument.
     * Arg5 is the third argument.
     * Arg6 is the fourth argument.
     */
    Call4: 112,
    /**
     * Identical to CallWithNewTarget, but allowing more arguments.
     * arg4 is a register containing a number, instead of a literal number.
     * This is done to decrease the size of this opcode.
     */
    CallWithNewTargetLong: 113,
    /**
     * A Metro require call.
     * Arg1 is the destination of the return value.
     * Arg2 is the closure to invoke.
     * Arg3 is the module index argument, as an immediate.
     */
    CallRequire: 114,
    /**
     * Call a builtin function.
     * Note this is NOT marked as a Ret target, because the callee is native
     * and therefore never JS.
     * Arg1 is the destination of the return value.
     * Arg2 is the builtin number.
     * Arg3 is the number of arguments, assumed to be found in reverse order
     *      from the end of the current frame.
     * thisArg is set to "undefined".
     */
    CallBuiltin: 115,
    /**
     * Call a builtin function.
     * Note this is NOT marked as a Ret target, because the callee is native
     * and therefore never JS.
     * Arg1 is the destination of the return value.
     * Arg2 is the builtin number.
     * Arg3 is the number of arguments, assumed to be found in reverse order
     *      from the end of the current frame.
     * thisArg is set to "undefined".
     */
    CallBuiltinLong: 116,
    /**
     * Get a closure from a builtin function.
     * Arg1 is the destination of the return value.
     * Arg2 is the builtin number.
     */
    GetBuiltinClosure: 117,
    /**
     * Return a value from the current function.
     * return Arg1;
     */
    Ret: 118,
    /**
     * Catch an exception (the first instruction in an exception handler).
     * } catch(Arg1) {
     */
    Catch: 119,
    /**
     * ES6 18.2.1.1 PerformEval(Arg2, evalRealm, strictCaller=true, direct=true)
     * Arg1 is the destination of the return value.
     * Arg2 is the eval text
     * Arg3 is a bool indicating strictCaller
     */
    DirectEval: 120,
    /**
     * Throw an exception.
     * throw Arg1;
     */
    Throw: 121,
    /**
     * If Arg2 is Empty, throw ReferenceError, otherwise move it into Arg1.
     * Arg1 is the destination of the return value
     * Arg2 is the value to check
     */
    ThrowIfEmpty: 122,
    /**
     * If Arg2 is Undefined, throw ReferenceError, otherwise move it into Arg1.
     * Arg1 is the destination of the return value
     * Arg2 is the value to check
     */
    ThrowIfUndefined: 123,
    /**
     * If Arg1 is not Empty, throw ReferenceError.
     * Arg1 is the checked this of a derived constructor.
     */
    ThrowIfThisInitialized: 124,
    /**
     * Implementation dependent debugger action.
     */
    Debugger: 125,
    /**
     * Fast check for an async interrupt request.
     */
    AsyncBreakCheck: 126,
    /**
     * Define a profile point.
     * Arg1 is the function local profile point index. The first one will have the
     * largest index. If there are more than 2^16 profile points in the function,
     * all the overflowed profile points have index zero.
     */
    ProfilePoint: 127,
    /**
     * Create a base class.
     * Arg1 is the output register for the the closure.
     * Arg2 is the output register for the home object.
     * Arg3 is the current environment.
     * Arg4 is index in the function table.
     */
    CreateBaseClass: 128,
    CreateBaseClassLongIndex: 129,
    /**
     * Create a derived class.
     * Arg1 is the output register for the the closure.
     * Arg2 is the output register for the home object.
     * Arg3 is the current environment.
     * Arg4 is the superClass.
     * Arg5 is index in the function table.
     */
    CreateDerivedClass: 130,
    CreateDerivedClassLongIndex: 131,
    /**
     * Create a closure.
     * Arg1 is the register in which to store the closure.
     * Arg2 is the parent environment of the closure, or undefined.
     * Arg3 is index in the function table.
     */
    CreateClosure: 132,
    CreateClosureLongIndex: 133,
    /**
     * Allocate an empty, uninitialized object to be used as the `this` parameter
     * in a `new` expression. Some closures are responsible for making their own
     * `this`, so in these cases this instruction will simply return undefined.
     * Arg1 is the destination register.
     * Arg2 is the constructor closure that will be invoked.
     * Arg3 is a cache index used to speed up fetching the new target prototype
     * property.
     */
    CreateThisForNew: 134,
    /**
     * Allocate an empty, uninitialized object to be used as the `this` parameter
     * in a `new` expression.
     * Arg1 is the destination register.
     * Arg2 is the constructor closure that will be invoked.
     * Arg3 is the new.target.
     * Arg4 is a cache index used to speed up fetching the new target prototype property.
     */
    CreateThisForSuper: 135,
    /**
     * Choose the result of a constructor: 'this' or a returned object.
     * Arg1 is the result.
     * Arg2 is the 'this' object used for the constructor.
     * Arg3 is the constructor's return value.
     * Arg1 = Arg3 instanceof Object ? Arg3 : Arg2
     */
    SelectObject: 136,
    /**
     * Load a function parameter by index. Starts at 0 with 'this'.
     * Arg1 = Arg2 == 0 ? this : arguments[Arg2 - 1];
     */
    LoadParam: 137,
    /**
     * Like LoadParam, but allows accessing arguments >= 255.
     */
    LoadParamLong: 138,
    /**
     * Load a constant integer value.
     */
    LoadConstUInt8: 139,
    LoadConstInt: 140,
    /**
     * Load a constant double value.
     */
    LoadConstDouble: 141,
    /**
     * Load a constant BigInt value by bigint table index.
     */
    LoadConstBigInt: 142,
    LoadConstBigIntLongIndex: 143,
    /**
     * Load a constant string value by string table index.
     */
    LoadConstString: 144,
    LoadConstStringLongIndex: 145,
    /**
     * Load common constants.
     */
    LoadConstEmpty: 146,
    LoadConstUndefined: 147,
    LoadConstNull: 148,
    LoadConstTrue: 149,
    LoadConstFalse: 150,
    LoadConstZero: 151,
    /**
     * Coerce a value assumed to contain 'this' to an object using non-strict
     * mode rules. Primitives are boxed, \c null or \c undefed produce the global
     * object.
     * Arg1 = coerce_to_object(Arg2)
     */
    CoerceThisNS: 152,
    /**
     * Obtain the raw \c this value and coerce it to an object. Equivalent to:
     * \code
     *     LoadParam    Arg1, #0
     *     CoerceThisNS Arg1, Arg1
     * \endcode
     */
    LoadThisNS: 153,
    /**
     * Convert a value to a number.
     * Arg1 = Arg2 - 0
     */
    ToNumber: 154,
    /**
     * Convert a value to a numberic.
     * Arg1 = ToNumeric(Arg2)
     */
    ToNumeric: 155,
    /**
     * Convert a value to a 32-bit signed integer.
     * Arg1 = Arg2 | 0
     */
    ToInt32: 156,
    /**
     * Convert a value to a string as if evaluating the expression:
     *     Arg1 = "" + Arg2
     * In practice this means
     *     Arg1 = ToString(ToPrimitive(Arg2, PreferredType::NONE))
     * with ToPrimitive (ES5.1 9.1) and ToString (ES5.1 9.8).
     */
    AddEmptyString: 157,
    /**
     * Create a new primitive symbol, taking in a string description as input.
     * This is almost equivalent to the following JS, with the important distinction
     * an object is not computed- just the raw SymbolID.
     *   Arg1 is the result.
     *   Arg2 is the string id for the symbol description.
     *   Arg1 = new Symbol(Arg2)
     */
    CreatePrivateName: 158,
    /**
     * Get a property of the 'arguments' array by value.
     * Arg1 is the result.
     * Arg2 is the index.
     * Arg3 is the lazy loaded register.
     * Arg1 = arguments[Arg2]
     */
    GetArgumentsPropByValLoose: 159,
    GetArgumentsPropByValStrict: 160,
    /**
     * Get the length of the 'arguments' array.
     * Arg1 is the result.
     * Arg2 is the lazy loaded register.
     * Arg1 = arguments.length
     */
    GetArgumentsLength: 161,
    /**
     * Create an actual 'arguments' array, if get-by-index and length isn't enough.
     * Arg1 is the lazy loaded register, which afterwards will contain a proper
     *      object that can be used by non-*Arguments* opcodes like Return.
     */
    ReifyArgumentsStrict: 162,
    ReifyArgumentsLoose: 163,
    /**
     * Convert a value to a property key, used to evaluate a ComputedPropertyName.
     * Arg1 = ToPropertyKey(Arg2)
     */
    ToPropertyKey: 164,
    /**
     * Create a regular expression.
     * Arg1 is the result.
     * Arg2 is the string index of the pattern.
     * Arg3 is the string index of the flags.
     * Arg4 is the regexp bytecode index in the regexp table.
     */
    CreateRegExp: 165,
    /**
     * Jump table switch - using a table of offset, jump to the offset of the given
     * input or to the default block if out of range (or not right type)
     * Arg 1 is the value to be branched upon
     * Arg 2 is the relative offset of the jump table to be used by this
     *   instruction. Jump tables are appended to the bytecode.
     * Arg 3 is the relative offset for the "default" jump.
     * Arg 4 is the unsigned min value, if arg 1 is/ less than this value jmp to
     *   default block
     * Arg 5 is the unsigned max value, if arg 1 is greater than this value jmp to
     *   default block.
     * Given the above, the jump table entry for a given value (that is in range)
     * is located at offset ip + arg2 + arg1 - arg4. We subtract arg4 to avoid
     * wasting space when compiling denses switches that do not start at zero. Note
     * that Arg2 is *unaligned* it is dynamically aligned at runtime.
     */
    UIntSwitchImm: 166,
    /**
     * All-string switch (switch all of whose case labels are string literals).
     * Arg 1 is the value to be branched upon
     * Arg 2 is a global index for this StringSwitchImm instruction in the
     * bytecode file.
     * Arg 3 is the relative offset of the string switch table.  A string switch
     *   table is a sequence of pairs:
     *   <UInt32 string table index, UInt32 jump targets>
     * Arg 4 is the relative offset for the "default" jump.
     * Arg 5 is the size of the string switch table.
     * Given the above, the jump table entry for a given value (that is in range)
     * is located at offset ip + arg3.  Note that Arg3 is *unaligned*; it is
     * dynamically aligned at runtime.
     */
    StringSwitchImm: 167,
    /**
     * Create a generator.
     * Arg1 is the register in which to store the generator.
     * Arg2 is the parent environment of the generator, or undefined.
     * Arg3 is index in the function table.
     */
    CreateGenerator: 168,
    CreateGeneratorLongIndex: 169,
    /**
     * Arg1 [out] is the result iterator or index.
     * Arg2 [in/out] is the source. Output for either the source or next method.
     * If source is an array with an unmodified [Symbol.iterator], the result is
     * 0. Else the result is source[Symbol.iterator] and the output is the .next()
     * method on the iterator.
     * See IR.md for IteratorBeginInst.
     */
    IteratorBegin: 170,
    /**
     * Arg1 [out] is the result, or undefined if done.
     * Arg2 [in/out] is the iterator or index.
     * Arg2 [in] is the source or the next method.
     * If iterator is undefined, result = undefined.
     * If iterator is a number:
     *   If iterator is less than source.length, return source[iterator++]
     *   Else iterator = undefined and result = undefined
     * Else:
     *   n = iterator.next()
     *   If n.done, iterator = undefined and result = undefined.
     *   Else result = n.value
     * See IR.md for IteratorNextInst.
     */
    IteratorNext: 171,
    /**
     * Arg1 [in] is the iterator or array index.
     * Arg2 is a bool indicating whether to ignore the inner exception.
     * If the iterator is an object, call iterator.return().
     * If Arg2 is true, ignore exceptions which are thrown by iterator.return().
     * See IR.md for IteratorCloseInst.
     */
    IteratorClose: 172,
    /**
     * Arg1 [out] is the result.
     * Arg2 [in] is the source (must be an object).
     */
    TypedLoadParent: 173,
    /**
     * Unconditional branch to Arg1.
     */
    Jmp: 174,
    /**
     * Unconditional branch to Arg1.
     */
    JmpLong: 175,
    /**
     * Conditional branches to Arg1 based on Arg2.
     */
    JmpTrue: 176,
    /**
     * Conditional branches to Arg1 based on Arg2.
     */
    JmpTrueLong: 177,
    JmpFalse: 178,
    JmpFalseLong: 179,
    /**
     * Jump if the value is undefined.
     */
    JmpUndefined: 180,
    /**
     * Jump if the value is undefined.
     */
    JmpUndefinedLong: 181,
    /**
     * Jump if the type matches the TypeOfIsTypes in Arg3.
     * Arg1 is the target.
     * Arg2 is the value to test.
     * Arg3 is the TypeOfIsTypes (see Typeof.h).
     */
    JmpTypeOfIs: 182,
    /**
     * Not conditionals are required for NaN comparisons
     * Since we want to be able to reorder targets to allow for fall-throughs,
     * we need to be able to say "jump when not less than to BB2" instead of
     * "jump when less than to BB1".
     * Since NaN comparisons always return false, "not less" != "greater or equal"
     */
    JLess: 183,
    /**
     * Not conditionals are required for NaN comparisons
     * Since we want to be able to reorder targets to allow for fall-throughs,
     * we need to be able to say "jump when not less than to BB2" instead of
     * "jump when less than to BB1".
     * Since NaN comparisons always return false, "not less" != "greater or equal"
     */
    JLessLong: 184,
    JNotLess: 185,
    JNotLessLong: 186,
    JLessN: 187,
    JLessNLong: 188,
    JNotLessN: 189,
    JNotLessNLong: 190,
    JLessEqual: 191,
    JLessEqualLong: 192,
    JNotLessEqual: 193,
    JNotLessEqualLong: 194,
    JLessEqualN: 195,
    JLessEqualNLong: 196,
    JNotLessEqualN: 197,
    JNotLessEqualNLong: 198,
    JGreater: 199,
    JGreaterLong: 200,
    JNotGreater: 201,
    JNotGreaterLong: 202,
    JGreaterEqual: 203,
    JGreaterEqualLong: 204,
    JNotGreaterEqual: 205,
    JNotGreaterEqualLong: 206,
    JEqual: 207,
    JEqualLong: 208,
    JNotEqual: 209,
    JNotEqualLong: 210,
    JStrictEqual: 211,
    JStrictEqualLong: 212,
    JStrictNotEqual: 213,
    JStrictNotEqualLong: 214,
    JmpBuiltinIs: 215,
    JmpBuiltinIsLong: 216,
    JmpBuiltinIsNot: 217,
    JmpBuiltinIsNotLong: 218,
} as const;

export type Opcode = typeof Opcode[keyof typeof Opcode];

export const opcodeNames = {
    0: "Unreachable",
    1: "NewObjectWithBuffer",
    2: "NewObjectWithBufferLong",
    3: "NewObjectWithBufferAndParent",
    4: "NewObject",
    5: "NewObjectWithParent",
    6: "NewArrayWithBuffer",
    7: "NewArrayWithBufferLong",
    8: "NewArray",
    9: "NewFastArray",
    10: "FastArrayLength",
    11: "FastArrayLoad",
    12: "FastArrayStore",
    13: "FastArrayPush",
    14: "FastArrayAppend",
    15: "CacheNewObject",
    16: "Mov",
    17: "MovLong",
    18: "Negate",
    19: "Not",
    20: "BitNot",
    21: "TypeOf",
    22: "Eq",
    23: "StrictEq",
    24: "Neq",
    25: "StrictNeq",
    26: "Less",
    27: "LessEq",
    28: "Greater",
    29: "GreaterEq",
    30: "Add",
    31: "AddN",
    32: "AddS",
    33: "Mul",
    34: "MulN",
    35: "Div",
    36: "DivN",
    37: "Mod",
    38: "Sub",
    39: "SubN",
    40: "LShift",
    41: "RShift",
    42: "URshift",
    43: "BitAnd",
    44: "BitXor",
    45: "BitOr",
    46: "Inc",
    47: "Dec",
    48: "InstanceOf",
    49: "IsIn",
    50: "PrivateIsIn",
    51: "TypeOfIs",
    52: "GetParentEnvironment",
    53: "GetEnvironment",
    54: "GetClosureEnvironment",
    55: "StoreToEnvironment",
    56: "StoreToEnvironmentL",
    57: "StoreNPToEnvironment",
    58: "StoreNPToEnvironmentL",
    59: "LoadFromEnvironment",
    60: "LoadFromEnvironmentL",
    61: "GetGlobalObject",
    62: "GetNewTarget",
    63: "LoadParentNoTraps",
    64: "CreateFunctionEnvironment",
    65: "CreateTopLevelEnvironment",
    66: "CreateEnvironment",
    67: "DeclareGlobalVar",
    68: "GetByIdShort",
    69: "GetById",
    70: "GetByIdLong",
    71: "GetByIdWithReceiverLong",
    72: "TryGetById",
    73: "TryGetByIdLong",
    74: "PutByIdLoose",
    75: "PutByIdStrict",
    76: "PutByIdLooseLong",
    77: "PutByIdStrictLong",
    78: "TryPutByIdLoose",
    79: "TryPutByIdStrict",
    80: "TryPutByIdLooseLong",
    81: "TryPutByIdStrictLong",
    82: "PutOwnBySlotIdx",
    83: "PutOwnBySlotIdxLong",
    84: "GetOwnBySlotIdx",
    85: "GetOwnBySlotIdxLong",
    86: "DefineOwnById",
    87: "DefineOwnByIdLong",
    88: "DefineOwnByIndex",
    89: "DefineOwnByIndexL",
    90: "DefineOwnInDenseArray",
    91: "DefineOwnInDenseArrayL",
    92: "DefineOwnByVal",
    93: "GetByVal",
    94: "GetByIndex",
    95: "GetByValWithReceiver",
    96: "PutByValLoose",
    97: "PutByValStrict",
    98: "PutByValWithReceiver",
    99: "DelByVal",
    100: "AddOwnPrivateBySym",
    101: "GetOwnPrivateBySym",
    102: "PutOwnPrivateBySym",
    103: "DefineOwnGetterSetterByVal",
    104: "GetPNameList",
    105: "GetNextPName",
    106: "Call",
    107: "Construct",
    108: "Call1",
    109: "CallWithNewTarget",
    110: "Call2",
    111: "Call3",
    112: "Call4",
    113: "CallWithNewTargetLong",
    114: "CallRequire",
    115: "CallBuiltin",
    116: "CallBuiltinLong",
    117: "GetBuiltinClosure",
    118: "Ret",
    119: "Catch",
    120: "DirectEval",
    121: "Throw",
    122: "ThrowIfEmpty",
    123: "ThrowIfUndefined",
    124: "ThrowIfThisInitialized",
    125: "Debugger",
    126: "AsyncBreakCheck",
    127: "ProfilePoint",
    128: "CreateBaseClass",
    129: "CreateBaseClassLongIndex",
    130: "CreateDerivedClass",
    131: "CreateDerivedClassLongIndex",
    132: "CreateClosure",
    133: "CreateClosureLongIndex",
    134: "CreateThisForNew",
    135: "CreateThisForSuper",
    136: "SelectObject",
    137: "LoadParam",
    138: "LoadParamLong",
    139: "LoadConstUInt8",
    140: "LoadConstInt",
    141: "LoadConstDouble",
    142: "LoadConstBigInt",
    143: "LoadConstBigIntLongIndex",
    144: "LoadConstString",
    145: "LoadConstStringLongIndex",
    146: "LoadConstEmpty",
    147: "LoadConstUndefined",
    148: "LoadConstNull",
    149: "LoadConstTrue",
    150: "LoadConstFalse",
    151: "LoadConstZero",
    152: "CoerceThisNS",
    153: "LoadThisNS",
    154: "ToNumber",
    155: "ToNumeric",
    156: "ToInt32",
    157: "AddEmptyString",
    158: "CreatePrivateName",
    159: "GetArgumentsPropByValLoose",
    160: "GetArgumentsPropByValStrict",
    161: "GetArgumentsLength",
    162: "ReifyArgumentsStrict",
    163: "ReifyArgumentsLoose",
    164: "ToPropertyKey",
    165: "CreateRegExp",
    166: "UIntSwitchImm",
    167: "StringSwitchImm",
    168: "CreateGenerator",
    169: "CreateGeneratorLongIndex",
    170: "IteratorBegin",
    171: "IteratorNext",
    172: "IteratorClose",
    173: "TypedLoadParent",
    174: "Jmp",
    175: "JmpLong",
    176: "JmpTrue",
    177: "JmpTrueLong",
    178: "JmpFalse",
    179: "JmpFalseLong",
    180: "JmpUndefined",
    181: "JmpUndefinedLong",
    182: "JmpTypeOfIs",
    183: "JLess",
    184: "JLessLong",
    185: "JNotLess",
    186: "JNotLessLong",
    187: "JLessN",
    188: "JLessNLong",
    189: "JNotLessN",
    190: "JNotLessNLong",
    191: "JLessEqual",
    192: "JLessEqualLong",
    193: "JNotLessEqual",
    194: "JNotLessEqualLong",
    195: "JLessEqualN",
    196: "JLessEqualNLong",
    197: "JNotLessEqualN",
    198: "JNotLessEqualNLong",
    199: "JGreater",
    200: "JGreaterLong",
    201: "JNotGreater",
    202: "JNotGreaterLong",
    203: "JGreaterEqual",
    204: "JGreaterEqualLong",
    205: "JNotGreaterEqual",
    206: "JNotGreaterEqualLong",
    207: "JEqual",
    208: "JEqualLong",
    209: "JNotEqual",
    210: "JNotEqualLong",
    211: "JStrictEqual",
    212: "JStrictEqualLong",
    213: "JStrictNotEqual",
    214: "JStrictNotEqualLong",
    215: "JmpBuiltinIs",
    216: "JmpBuiltinIsLong",
    217: "JmpBuiltinIsNot",
    218: "JmpBuiltinIsNotLong",
} as const;

export type OpcodeMap<T> = Readonly<Partial<Record<Opcode, T>>>;

export type OperandSet = OpcodeMap<readonly number[]>;

/**
 * Argument type corresponding to {@link Opcode}.
 */
export const opcodeTypes = {
    [Opcode.Unreachable]: [],
    [Opcode.NewObjectWithBuffer]: [ArgType.Reg8, ArgType.UInt16, ArgType.UInt16],
    [Opcode.NewObjectWithBufferLong]: [ArgType.Reg8, ArgType.UInt32, ArgType.UInt32],
    [Opcode.NewObjectWithBufferAndParent]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt32, ArgType.UInt32],
    [Opcode.NewObject]: [ArgType.Reg8],
    [Opcode.NewObjectWithParent]: [ArgType.Reg8, ArgType.Reg8],
    [Opcode.NewArrayWithBuffer]: [ArgType.Reg8, ArgType.UInt16, ArgType.UInt16, ArgType.UInt16],
    [Opcode.NewArrayWithBufferLong]: [ArgType.Reg8, ArgType.UInt16, ArgType.UInt16, ArgType.UInt32],
    [Opcode.NewArray]: [ArgType.Reg8, ArgType.UInt16],
    [Opcode.NewFastArray]: [ArgType.Reg8, ArgType.UInt16],
    [Opcode.FastArrayLength]: [ArgType.Reg8, ArgType.Reg8],
    [Opcode.FastArrayLoad]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.FastArrayStore]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.FastArrayPush]: [ArgType.Reg8, ArgType.Reg8],
    [Opcode.FastArrayAppend]: [ArgType.Reg8, ArgType.Reg8],
    [Opcode.CacheNewObject]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt32, ArgType.UInt8],
    [Opcode.Mov]: [ArgType.Reg8, ArgType.Reg8],
    [Opcode.MovLong]: [ArgType.Reg32, ArgType.Reg32],
    [Opcode.Negate]: [ArgType.Reg8, ArgType.Reg8],
    [Opcode.Not]: [ArgType.Reg8, ArgType.Reg8],
    [Opcode.BitNot]: [ArgType.Reg8, ArgType.Reg8],
    [Opcode.TypeOf]: [ArgType.Reg8, ArgType.Reg8],
    [Opcode.Eq]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.StrictEq]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.Neq]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.StrictNeq]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.Less]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.LessEq]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.Greater]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.GreaterEq]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.Add]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.AddN]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.AddS]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.Mul]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.MulN]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.Div]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.DivN]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.Mod]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.Sub]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.SubN]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.LShift]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.RShift]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.URshift]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.BitAnd]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.BitXor]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.BitOr]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.Inc]: [ArgType.Reg8, ArgType.Reg8],
    [Opcode.Dec]: [ArgType.Reg8, ArgType.Reg8],
    [Opcode.InstanceOf]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.IsIn]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.PrivateIsIn]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.TypeOfIs]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt16],
    [Opcode.GetParentEnvironment]: [ArgType.Reg8, ArgType.UInt8],
    [Opcode.GetEnvironment]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8],
    [Opcode.GetClosureEnvironment]: [ArgType.Reg8, ArgType.Reg8],
    [Opcode.StoreToEnvironment]: [ArgType.Reg8, ArgType.UInt8, ArgType.Reg8],
    [Opcode.StoreToEnvironmentL]: [ArgType.Reg8, ArgType.UInt16, ArgType.Reg8],
    [Opcode.StoreNPToEnvironment]: [ArgType.Reg8, ArgType.UInt8, ArgType.Reg8],
    [Opcode.StoreNPToEnvironmentL]: [ArgType.Reg8, ArgType.UInt16, ArgType.Reg8],
    [Opcode.LoadFromEnvironment]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8],
    [Opcode.LoadFromEnvironmentL]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt16],
    [Opcode.GetGlobalObject]: [ArgType.Reg8],
    [Opcode.GetNewTarget]: [ArgType.Reg8],
    [Opcode.LoadParentNoTraps]: [ArgType.Reg8, ArgType.Reg8],
    [Opcode.CreateFunctionEnvironment]: [ArgType.Reg8, ArgType.UInt8],
    [Opcode.CreateTopLevelEnvironment]: [ArgType.Reg8, ArgType.UInt32],
    [Opcode.CreateEnvironment]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt32],
    [Opcode.DeclareGlobalVar]: [ArgType.UInt32],
    [Opcode.GetByIdShort]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8, ArgType.UInt8],
    [Opcode.GetById]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8, ArgType.UInt16],
    [Opcode.GetByIdLong]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8, ArgType.UInt32],
    [Opcode.GetByIdWithReceiverLong]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8, ArgType.Reg8, ArgType.UInt32],
    [Opcode.TryGetById]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8, ArgType.UInt16],
    [Opcode.TryGetByIdLong]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8, ArgType.UInt32],
    [Opcode.PutByIdLoose]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8, ArgType.UInt16],
    [Opcode.PutByIdStrict]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8, ArgType.UInt16],
    [Opcode.PutByIdLooseLong]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8, ArgType.UInt32],
    [Opcode.PutByIdStrictLong]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8, ArgType.UInt32],
    [Opcode.TryPutByIdLoose]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8, ArgType.UInt16],
    [Opcode.TryPutByIdStrict]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8, ArgType.UInt16],
    [Opcode.TryPutByIdLooseLong]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8, ArgType.UInt32],
    [Opcode.TryPutByIdStrictLong]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8, ArgType.UInt32],
    [Opcode.PutOwnBySlotIdx]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8],
    [Opcode.PutOwnBySlotIdxLong]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt32],
    [Opcode.GetOwnBySlotIdx]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8],
    [Opcode.GetOwnBySlotIdxLong]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt32],
    [Opcode.DefineOwnById]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8, ArgType.UInt16],
    [Opcode.DefineOwnByIdLong]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8, ArgType.UInt32],
    [Opcode.DefineOwnByIndex]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8],
    [Opcode.DefineOwnByIndexL]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt32],
    [Opcode.DefineOwnInDenseArray]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8],
    [Opcode.DefineOwnInDenseArrayL]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt16],
    [Opcode.DefineOwnByVal]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8, ArgType.UInt8],
    [Opcode.GetByVal]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.GetByIndex]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8],
    [Opcode.GetByValWithReceiver]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.PutByValLoose]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.PutByValStrict]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.PutByValWithReceiver]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8, ArgType.Reg8, ArgType.UInt8],
    [Opcode.DelByVal]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8, ArgType.UInt8],
    [Opcode.AddOwnPrivateBySym]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.GetOwnPrivateBySym]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8, ArgType.Reg8],
    [Opcode.PutOwnPrivateBySym]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8, ArgType.Reg8],
    [Opcode.DefineOwnGetterSetterByVal]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8, ArgType.Reg8, ArgType.UInt8],
    [Opcode.GetPNameList]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.GetNextPName]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.Call]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8],
    [Opcode.Construct]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8],
    [Opcode.Call1]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.CallWithNewTarget]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8, ArgType.UInt8],
    [Opcode.Call2]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.Call3]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.Call4]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8, ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.CallWithNewTargetLong]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.CallRequire]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt32],
    [Opcode.CallBuiltin]: [ArgType.Reg8, ArgType.UInt8, ArgType.UInt8],
    [Opcode.CallBuiltinLong]: [ArgType.Reg8, ArgType.UInt8, ArgType.UInt32],
    [Opcode.GetBuiltinClosure]: [ArgType.Reg8, ArgType.UInt8],
    [Opcode.Ret]: [ArgType.Reg8],
    [Opcode.Catch]: [ArgType.Reg8],
    [Opcode.DirectEval]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8],
    [Opcode.Throw]: [ArgType.Reg8],
    [Opcode.ThrowIfEmpty]: [ArgType.Reg8, ArgType.Reg8],
    [Opcode.ThrowIfUndefined]: [ArgType.Reg8, ArgType.Reg8],
    [Opcode.ThrowIfThisInitialized]: [ArgType.Reg8],
    [Opcode.Debugger]: [],
    [Opcode.AsyncBreakCheck]: [],
    [Opcode.ProfilePoint]: [ArgType.UInt16],
    [Opcode.CreateBaseClass]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8, ArgType.UInt16],
    [Opcode.CreateBaseClassLongIndex]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8, ArgType.UInt32],
    [Opcode.CreateDerivedClass]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8, ArgType.Reg8, ArgType.UInt16],
    [Opcode.CreateDerivedClassLongIndex]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8, ArgType.Reg8, ArgType.UInt32],
    [Opcode.CreateClosure]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt16],
    [Opcode.CreateClosureLongIndex]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt32],
    [Opcode.CreateThisForNew]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt8],
    [Opcode.CreateThisForSuper]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8, ArgType.UInt8],
    [Opcode.SelectObject]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.LoadParam]: [ArgType.Reg8, ArgType.UInt8],
    [Opcode.LoadParamLong]: [ArgType.Reg8, ArgType.UInt32],
    [Opcode.LoadConstUInt8]: [ArgType.Reg8, ArgType.UInt8],
    [Opcode.LoadConstInt]: [ArgType.Reg8, ArgType.Imm32],
    [Opcode.LoadConstDouble]: [ArgType.Reg8, ArgType.Double],
    [Opcode.LoadConstBigInt]: [ArgType.Reg8, ArgType.UInt16],
    [Opcode.LoadConstBigIntLongIndex]: [ArgType.Reg8, ArgType.UInt32],
    [Opcode.LoadConstString]: [ArgType.Reg8, ArgType.UInt16],
    [Opcode.LoadConstStringLongIndex]: [ArgType.Reg8, ArgType.UInt32],
    [Opcode.LoadConstEmpty]: [ArgType.Reg8],
    [Opcode.LoadConstUndefined]: [ArgType.Reg8],
    [Opcode.LoadConstNull]: [ArgType.Reg8],
    [Opcode.LoadConstTrue]: [ArgType.Reg8],
    [Opcode.LoadConstFalse]: [ArgType.Reg8],
    [Opcode.LoadConstZero]: [ArgType.Reg8],
    [Opcode.CoerceThisNS]: [ArgType.Reg8, ArgType.Reg8],
    [Opcode.LoadThisNS]: [ArgType.Reg8],
    [Opcode.ToNumber]: [ArgType.Reg8, ArgType.Reg8],
    [Opcode.ToNumeric]: [ArgType.Reg8, ArgType.Reg8],
    [Opcode.ToInt32]: [ArgType.Reg8, ArgType.Reg8],
    [Opcode.AddEmptyString]: [ArgType.Reg8, ArgType.Reg8],
    [Opcode.CreatePrivateName]: [ArgType.Reg8, ArgType.UInt32],
    [Opcode.GetArgumentsPropByValLoose]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.GetArgumentsPropByValStrict]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.GetArgumentsLength]: [ArgType.Reg8, ArgType.Reg8],
    [Opcode.ReifyArgumentsStrict]: [ArgType.Reg8],
    [Opcode.ReifyArgumentsLoose]: [ArgType.Reg8],
    [Opcode.ToPropertyKey]: [ArgType.Reg8, ArgType.Reg8],
    [Opcode.CreateRegExp]: [ArgType.Reg8, ArgType.UInt32, ArgType.UInt32, ArgType.UInt32],
    [Opcode.UIntSwitchImm]: [ArgType.Reg8, ArgType.UInt32, ArgType.Addr32, ArgType.UInt32, ArgType.UInt32],
    [Opcode.StringSwitchImm]: [ArgType.Reg8, ArgType.UInt32, ArgType.UInt32, ArgType.Addr32, ArgType.UInt32],
    [Opcode.CreateGenerator]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt16],
    [Opcode.CreateGeneratorLongIndex]: [ArgType.Reg8, ArgType.Reg8, ArgType.UInt32],
    [Opcode.IteratorBegin]: [ArgType.Reg8, ArgType.Reg8],
    [Opcode.IteratorNext]: [ArgType.Reg8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.IteratorClose]: [ArgType.Reg8, ArgType.UInt8],
    [Opcode.TypedLoadParent]: [ArgType.Reg8, ArgType.Reg8],
    [Opcode.Jmp]: [ArgType.Addr8],
    [Opcode.JmpLong]: [ArgType.Addr32],
    [Opcode.JmpTrue]: [ArgType.Addr8, ArgType.Reg8],
    [Opcode.JmpTrueLong]: [ArgType.Addr32, ArgType.Reg8],
    [Opcode.JmpFalse]: [ArgType.Addr8, ArgType.Reg8],
    [Opcode.JmpFalseLong]: [ArgType.Addr32, ArgType.Reg8],
    [Opcode.JmpUndefined]: [ArgType.Addr8, ArgType.Reg8],
    [Opcode.JmpUndefinedLong]: [ArgType.Addr32, ArgType.Reg8],
    [Opcode.JmpTypeOfIs]: [ArgType.Addr32, ArgType.Reg8, ArgType.UInt16],
    [Opcode.JLess]: [ArgType.Addr8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JLessLong]: [ArgType.Addr32, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JNotLess]: [ArgType.Addr8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JNotLessLong]: [ArgType.Addr32, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JLessN]: [ArgType.Addr8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JLessNLong]: [ArgType.Addr32, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JNotLessN]: [ArgType.Addr8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JNotLessNLong]: [ArgType.Addr32, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JLessEqual]: [ArgType.Addr8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JLessEqualLong]: [ArgType.Addr32, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JNotLessEqual]: [ArgType.Addr8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JNotLessEqualLong]: [ArgType.Addr32, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JLessEqualN]: [ArgType.Addr8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JLessEqualNLong]: [ArgType.Addr32, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JNotLessEqualN]: [ArgType.Addr8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JNotLessEqualNLong]: [ArgType.Addr32, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JGreater]: [ArgType.Addr8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JGreaterLong]: [ArgType.Addr32, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JNotGreater]: [ArgType.Addr8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JNotGreaterLong]: [ArgType.Addr32, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JGreaterEqual]: [ArgType.Addr8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JGreaterEqualLong]: [ArgType.Addr32, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JNotGreaterEqual]: [ArgType.Addr8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JNotGreaterEqualLong]: [ArgType.Addr32, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JEqual]: [ArgType.Addr8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JEqualLong]: [ArgType.Addr32, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JNotEqual]: [ArgType.Addr8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JNotEqualLong]: [ArgType.Addr32, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JStrictEqual]: [ArgType.Addr8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JStrictEqualLong]: [ArgType.Addr32, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JStrictNotEqual]: [ArgType.Addr8, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JStrictNotEqualLong]: [ArgType.Addr32, ArgType.Reg8, ArgType.Reg8],
    [Opcode.JmpBuiltinIs]: [ArgType.Addr8, ArgType.UInt8, ArgType.Reg8],
    [Opcode.JmpBuiltinIsLong]: [ArgType.Addr32, ArgType.UInt8, ArgType.Reg8],
    [Opcode.JmpBuiltinIsNot]: [ArgType.Addr8, ArgType.UInt8, ArgType.Reg8],
    [Opcode.JmpBuiltinIsNotLong]: [ArgType.Addr32, ArgType.UInt8, ArgType.Reg8],
} as const;

/**
 * Opcodes which have operands referring to the bigint table.
 */
const BIGINT_OPERANDS = {
    [Opcode.LoadConstBigInt]: [1],
    [Opcode.LoadConstBigIntLongIndex]: [1],
} as const;
export type BigIntOperands = typeof BIGINT_OPERANDS;
export const bigintOperands: OperandSet = BIGINT_OPERANDS;

/**
 * Opcodes which have operands referring to the function table.
 */
const FUNCTION_OPERANDS = {
    [Opcode.CreateClosure]: [2],
    [Opcode.CreateClosureLongIndex]: [2],
    [Opcode.CreateGenerator]: [2],
    [Opcode.CreateGeneratorLongIndex]: [2],
} as const;
export type FunctionOperands = typeof FUNCTION_OPERANDS;
export const functionOperands: OperandSet = FUNCTION_OPERANDS;

/**
 * Opcodes which have operands referring to the string table.
 */
const STRING_OPERANDS = {
    [Opcode.DeclareGlobalVar]: [0],
    [Opcode.GetByIdShort]: [3],
    [Opcode.GetById]: [3],
    [Opcode.GetByIdLong]: [3],
    [Opcode.GetByIdWithReceiverLong]: [4],
    [Opcode.TryGetById]: [3],
    [Opcode.TryGetByIdLong]: [3],
    [Opcode.PutByIdLoose]: [3],
    [Opcode.PutByIdStrict]: [3],
    [Opcode.PutByIdLooseLong]: [3],
    [Opcode.PutByIdStrictLong]: [3],
    [Opcode.TryPutByIdLoose]: [3],
    [Opcode.TryPutByIdStrict]: [3],
    [Opcode.TryPutByIdLooseLong]: [3],
    [Opcode.TryPutByIdStrictLong]: [3],
    [Opcode.DefineOwnByIdLong]: [3],
    [Opcode.LoadConstString]: [1],
    [Opcode.LoadConstStringLongIndex]: [1],
    [Opcode.CreatePrivateName]: [1],
    [Opcode.CreateRegExp]: [1, 2],
} as const;
export type StringOperands = typeof STRING_OPERANDS;
export const stringOperands: OperandSet = STRING_OPERANDS;

export const Builtin = {
    "Array.isArray": 0,
    "Date.UTC": 1,
    "Date.parse": 2,
    "JSON.parse": 3,
    "JSON.stringify": 4,
    "Math.abs": 5,
    "Math.acos": 6,
    "Math.asin": 7,
    "Math.atan": 8,
    "Math.atan2": 9,
    "Math.ceil": 10,
    "Math.cos": 11,
    "Math.exp": 12,
    "Math.floor": 13,
    "Math.hypot": 14,
    "Math.imul": 15,
    "Math.log": 16,
    "Math.max": 17,
    "Math.min": 18,
    "Math.pow": 19,
    "Math.round": 20,
    "Math.sin": 21,
    "Math.sqrt": 22,
    "Math.tan": 23,
    "Math.trunc": 24,
    "Object.create": 25,
    "Object.defineProperties": 26,
    "Object.defineProperty": 27,
    "Object.freeze": 28,
    "Object.getOwnPropertyDescriptor": 29,
    "Object.getOwnPropertyNames": 30,
    "Object.getPrototypeOf": 31,
    "Object.isExtensible": 32,
    "Object.isFrozen": 33,
    "Object.keys": 34,
    "Object.seal": 35,
    "String.fromCharCode": 36,
    "silentSetPrototypeOf": 37,
    "requireFast": 38,
    "getTemplateObject": 39,
    "ensureObject": 40,
    "getMethod": 41,
    "throwTypeError": 42,
    "throwReferenceError": 43,
    "copyDataProperties": 44,
    "copyRestArgs": 45,
    "arraySpread": 46,
    "apply": 47,
    "applyArguments": 48,
    "applyWithNewTarget": 49,
    "exportAll": 50,
    "exponentiationOperator": 51,
    "initRegexNamedGroups": 52,
    "functionPrototypeApply": 53,
    "functionPrototypeCall": 54,
} as const;

export type Builtin = typeof Builtin[keyof typeof Builtin];

export const builtinNames = {
    0: "Array.isArray",
    1: "Date.UTC",
    2: "Date.parse",
    3: "JSON.parse",
    4: "JSON.stringify",
    5: "Math.abs",
    6: "Math.acos",
    7: "Math.asin",
    8: "Math.atan",
    9: "Math.atan2",
    10: "Math.ceil",
    11: "Math.cos",
    12: "Math.exp",
    13: "Math.floor",
    14: "Math.hypot",
    15: "Math.imul",
    16: "Math.log",
    17: "Math.max",
    18: "Math.min",
    19: "Math.pow",
    20: "Math.round",
    21: "Math.sin",
    22: "Math.sqrt",
    23: "Math.tan",
    24: "Math.trunc",
    25: "Object.create",
    26: "Object.defineProperties",
    27: "Object.defineProperty",
    28: "Object.freeze",
    29: "Object.getOwnPropertyDescriptor",
    30: "Object.getOwnPropertyNames",
    31: "Object.getPrototypeOf",
    32: "Object.isExtensible",
    33: "Object.isFrozen",
    34: "Object.keys",
    35: "Object.seal",
    36: "String.fromCharCode",
    37: "silentSetPrototypeOf",
    38: "requireFast",
    39: "getTemplateObject",
    40: "ensureObject",
    41: "getMethod",
    42: "throwTypeError",
    43: "throwReferenceError",
    44: "copyDataProperties",
    45: "copyRestArgs",
    46: "arraySpread",
    47: "apply",
    48: "applyArguments",
    49: "applyWithNewTarget",
    50: "exportAll",
    51: "exponentiationOperator",
    52: "initRegexNamedGroups",
    53: "functionPrototypeApply",
    54: "functionPrototypeCall",
};

/**
 * Longer version of opcodes, allowing higher values in their arguments.
 */
export const longOpcodes: OpcodeMap<Opcode> = {
    [Opcode.NewObjectWithBuffer]: Opcode.NewObjectWithBufferLong,
    [Opcode.NewArrayWithBuffer]: Opcode.NewArrayWithBufferLong,
    [Opcode.Mov]: Opcode.MovLong,
    [Opcode.StoreToEnvironment]: Opcode.StoreToEnvironmentL,
    [Opcode.StoreNPToEnvironment]: Opcode.StoreNPToEnvironmentL,
    [Opcode.LoadFromEnvironment]: Opcode.LoadFromEnvironmentL,
    [Opcode.GetByIdShort]: Opcode.GetById,
    [Opcode.GetById]: Opcode.GetByIdLong,
    [Opcode.TryGetById]: Opcode.TryGetByIdLong,
    [Opcode.PutByIdLoose]: Opcode.PutByIdLooseLong,
    [Opcode.PutByIdStrict]: Opcode.PutByIdStrictLong,
    [Opcode.TryPutByIdLoose]: Opcode.TryPutByIdLooseLong,
    [Opcode.TryPutByIdStrict]: Opcode.TryPutByIdStrictLong,
    [Opcode.PutOwnBySlotIdx]: Opcode.PutOwnBySlotIdxLong,
    [Opcode.GetOwnBySlotIdx]: Opcode.GetOwnBySlotIdxLong,
    [Opcode.DefineOwnById]: Opcode.DefineOwnByIdLong,
    [Opcode.DefineOwnByIndex]: Opcode.DefineOwnByIndexL,
    [Opcode.DefineOwnInDenseArray]: Opcode.DefineOwnInDenseArrayL,
    [Opcode.CallWithNewTarget]: Opcode.CallWithNewTargetLong,
    [Opcode.CallBuiltin]: Opcode.CallBuiltinLong,
    [Opcode.CreateBaseClass]: Opcode.CreateBaseClassLongIndex,
    [Opcode.CreateDerivedClass]: Opcode.CreateDerivedClassLongIndex,
    [Opcode.CreateClosure]: Opcode.CreateClosureLongIndex,
    [Opcode.LoadParam]: Opcode.LoadParamLong,
    [Opcode.LoadConstBigInt]: Opcode.LoadConstBigIntLongIndex,
    [Opcode.LoadConstString]: Opcode.LoadConstStringLongIndex,
    [Opcode.CreateGenerator]: Opcode.CreateGeneratorLongIndex,
    [Opcode.Jmp]: Opcode.JmpLong,
    [Opcode.JmpTrue]: Opcode.JmpTrueLong,
    [Opcode.JmpFalse]: Opcode.JmpFalseLong,
    [Opcode.JmpUndefined]: Opcode.JmpUndefinedLong,
    [Opcode.JLess]: Opcode.JLessLong,
    [Opcode.JNotLess]: Opcode.JNotLessLong,
    [Opcode.JLessN]: Opcode.JLessNLong,
    [Opcode.JNotLessN]: Opcode.JNotLessNLong,
    [Opcode.JLessEqual]: Opcode.JLessEqualLong,
    [Opcode.JNotLessEqual]: Opcode.JNotLessEqualLong,
    [Opcode.JLessEqualN]: Opcode.JLessEqualNLong,
    [Opcode.JNotLessEqualN]: Opcode.JNotLessEqualNLong,
    [Opcode.JGreater]: Opcode.JGreaterLong,
    [Opcode.JNotGreater]: Opcode.JNotGreaterLong,
    [Opcode.JGreaterEqual]: Opcode.JGreaterEqualLong,
    [Opcode.JNotGreaterEqual]: Opcode.JNotGreaterEqualLong,
    [Opcode.JEqual]: Opcode.JEqualLong,
    [Opcode.JNotEqual]: Opcode.JNotEqualLong,
    [Opcode.JStrictEqual]: Opcode.JStrictEqualLong,
    [Opcode.JStrictNotEqual]: Opcode.JStrictNotEqualLong,
    [Opcode.JmpBuiltinIs]: Opcode.JmpBuiltinIsLong,
    [Opcode.JmpBuiltinIsNot]: Opcode.JmpBuiltinIsNotLong,
};

/**
 * Normalised opcodes without a Short or Long suffix.
 */
export const canonicalOpcodes: Readonly<Record<Opcode, Opcode>> = {
    [Opcode.Unreachable]: Opcode.Unreachable,
    [Opcode.NewObjectWithBuffer]: Opcode.NewObjectWithBuffer,
    [Opcode.NewObjectWithBufferLong]: Opcode.NewObjectWithBuffer,
    [Opcode.NewObjectWithBufferAndParent]: Opcode.NewObjectWithBufferAndParent,
    [Opcode.NewObject]: Opcode.NewObject,
    [Opcode.NewObjectWithParent]: Opcode.NewObjectWithParent,
    [Opcode.NewArrayWithBuffer]: Opcode.NewArrayWithBuffer,
    [Opcode.NewArrayWithBufferLong]: Opcode.NewArrayWithBuffer,
    [Opcode.NewArray]: Opcode.NewArray,
    [Opcode.NewFastArray]: Opcode.NewFastArray,
    [Opcode.FastArrayLength]: Opcode.FastArrayLength,
    [Opcode.FastArrayLoad]: Opcode.FastArrayLoad,
    [Opcode.FastArrayStore]: Opcode.FastArrayStore,
    [Opcode.FastArrayPush]: Opcode.FastArrayPush,
    [Opcode.FastArrayAppend]: Opcode.FastArrayAppend,
    [Opcode.CacheNewObject]: Opcode.CacheNewObject,
    [Opcode.Mov]: Opcode.Mov,
    [Opcode.MovLong]: Opcode.Mov,
    [Opcode.Negate]: Opcode.Negate,
    [Opcode.Not]: Opcode.Not,
    [Opcode.BitNot]: Opcode.BitNot,
    [Opcode.TypeOf]: Opcode.TypeOf,
    [Opcode.Eq]: Opcode.Eq,
    [Opcode.StrictEq]: Opcode.StrictEq,
    [Opcode.Neq]: Opcode.Neq,
    [Opcode.StrictNeq]: Opcode.StrictNeq,
    [Opcode.Less]: Opcode.Less,
    [Opcode.LessEq]: Opcode.LessEq,
    [Opcode.Greater]: Opcode.Greater,
    [Opcode.GreaterEq]: Opcode.GreaterEq,
    [Opcode.Add]: Opcode.Add,
    [Opcode.AddN]: Opcode.AddN,
    [Opcode.AddS]: Opcode.AddS,
    [Opcode.Mul]: Opcode.Mul,
    [Opcode.MulN]: Opcode.MulN,
    [Opcode.Div]: Opcode.Div,
    [Opcode.DivN]: Opcode.DivN,
    [Opcode.Mod]: Opcode.Mod,
    [Opcode.Sub]: Opcode.Sub,
    [Opcode.SubN]: Opcode.SubN,
    [Opcode.LShift]: Opcode.LShift,
    [Opcode.RShift]: Opcode.RShift,
    [Opcode.URshift]: Opcode.URshift,
    [Opcode.BitAnd]: Opcode.BitAnd,
    [Opcode.BitXor]: Opcode.BitXor,
    [Opcode.BitOr]: Opcode.BitOr,
    [Opcode.Inc]: Opcode.Inc,
    [Opcode.Dec]: Opcode.Dec,
    [Opcode.InstanceOf]: Opcode.InstanceOf,
    [Opcode.IsIn]: Opcode.IsIn,
    [Opcode.PrivateIsIn]: Opcode.PrivateIsIn,
    [Opcode.TypeOfIs]: Opcode.TypeOfIs,
    [Opcode.GetParentEnvironment]: Opcode.GetParentEnvironment,
    [Opcode.GetEnvironment]: Opcode.GetEnvironment,
    [Opcode.GetClosureEnvironment]: Opcode.GetClosureEnvironment,
    [Opcode.StoreToEnvironment]: Opcode.StoreToEnvironment,
    [Opcode.StoreToEnvironmentL]: Opcode.StoreToEnvironment,
    [Opcode.StoreNPToEnvironment]: Opcode.StoreNPToEnvironment,
    [Opcode.StoreNPToEnvironmentL]: Opcode.StoreNPToEnvironment,
    [Opcode.LoadFromEnvironment]: Opcode.LoadFromEnvironment,
    [Opcode.LoadFromEnvironmentL]: Opcode.LoadFromEnvironment,
    [Opcode.GetGlobalObject]: Opcode.GetGlobalObject,
    [Opcode.GetNewTarget]: Opcode.GetNewTarget,
    [Opcode.LoadParentNoTraps]: Opcode.LoadParentNoTraps,
    [Opcode.CreateFunctionEnvironment]: Opcode.CreateFunctionEnvironment,
    [Opcode.CreateTopLevelEnvironment]: Opcode.CreateTopLevelEnvironment,
    [Opcode.CreateEnvironment]: Opcode.CreateEnvironment,
    [Opcode.DeclareGlobalVar]: Opcode.DeclareGlobalVar,
    [Opcode.GetByIdShort]: Opcode.GetById,
    [Opcode.GetById]: Opcode.GetById,
    [Opcode.GetByIdLong]: Opcode.GetById,
    [Opcode.GetByIdWithReceiverLong]: Opcode.GetByIdWithReceiverLong,
    [Opcode.TryGetById]: Opcode.TryGetById,
    [Opcode.TryGetByIdLong]: Opcode.TryGetById,
    [Opcode.PutByIdLoose]: Opcode.PutByIdLoose,
    [Opcode.PutByIdStrict]: Opcode.PutByIdStrict,
    [Opcode.PutByIdLooseLong]: Opcode.PutByIdLoose,
    [Opcode.PutByIdStrictLong]: Opcode.PutByIdStrict,
    [Opcode.TryPutByIdLoose]: Opcode.TryPutByIdLoose,
    [Opcode.TryPutByIdStrict]: Opcode.TryPutByIdStrict,
    [Opcode.TryPutByIdLooseLong]: Opcode.TryPutByIdLoose,
    [Opcode.TryPutByIdStrictLong]: Opcode.TryPutByIdStrict,
    [Opcode.PutOwnBySlotIdx]: Opcode.PutOwnBySlotIdx,
    [Opcode.PutOwnBySlotIdxLong]: Opcode.PutOwnBySlotIdx,
    [Opcode.GetOwnBySlotIdx]: Opcode.GetOwnBySlotIdx,
    [Opcode.GetOwnBySlotIdxLong]: Opcode.GetOwnBySlotIdx,
    [Opcode.DefineOwnById]: Opcode.DefineOwnById,
    [Opcode.DefineOwnByIdLong]: Opcode.DefineOwnById,
    [Opcode.DefineOwnByIndex]: Opcode.DefineOwnByIndex,
    [Opcode.DefineOwnByIndexL]: Opcode.DefineOwnByIndex,
    [Opcode.DefineOwnInDenseArray]: Opcode.DefineOwnInDenseArray,
    [Opcode.DefineOwnInDenseArrayL]: Opcode.DefineOwnInDenseArray,
    [Opcode.DefineOwnByVal]: Opcode.DefineOwnByVal,
    [Opcode.GetByVal]: Opcode.GetByVal,
    [Opcode.GetByIndex]: Opcode.GetByIndex,
    [Opcode.GetByValWithReceiver]: Opcode.GetByValWithReceiver,
    [Opcode.PutByValLoose]: Opcode.PutByValLoose,
    [Opcode.PutByValStrict]: Opcode.PutByValStrict,
    [Opcode.PutByValWithReceiver]: Opcode.PutByValWithReceiver,
    [Opcode.DelByVal]: Opcode.DelByVal,
    [Opcode.AddOwnPrivateBySym]: Opcode.AddOwnPrivateBySym,
    [Opcode.GetOwnPrivateBySym]: Opcode.GetOwnPrivateBySym,
    [Opcode.PutOwnPrivateBySym]: Opcode.PutOwnPrivateBySym,
    [Opcode.DefineOwnGetterSetterByVal]: Opcode.DefineOwnGetterSetterByVal,
    [Opcode.GetPNameList]: Opcode.GetPNameList,
    [Opcode.GetNextPName]: Opcode.GetNextPName,
    [Opcode.Call]: Opcode.Call,
    [Opcode.Construct]: Opcode.Construct,
    [Opcode.Call1]: Opcode.Call1,
    [Opcode.CallWithNewTarget]: Opcode.CallWithNewTarget,
    [Opcode.Call2]: Opcode.Call2,
    [Opcode.Call3]: Opcode.Call3,
    [Opcode.Call4]: Opcode.Call4,
    [Opcode.CallWithNewTargetLong]: Opcode.CallWithNewTarget,
    [Opcode.CallRequire]: Opcode.CallRequire,
    [Opcode.CallBuiltin]: Opcode.CallBuiltin,
    [Opcode.CallBuiltinLong]: Opcode.CallBuiltin,
    [Opcode.GetBuiltinClosure]: Opcode.GetBuiltinClosure,
    [Opcode.Ret]: Opcode.Ret,
    [Opcode.Catch]: Opcode.Catch,
    [Opcode.DirectEval]: Opcode.DirectEval,
    [Opcode.Throw]: Opcode.Throw,
    [Opcode.ThrowIfEmpty]: Opcode.ThrowIfEmpty,
    [Opcode.ThrowIfUndefined]: Opcode.ThrowIfUndefined,
    [Opcode.ThrowIfThisInitialized]: Opcode.ThrowIfThisInitialized,
    [Opcode.Debugger]: Opcode.Debugger,
    [Opcode.AsyncBreakCheck]: Opcode.AsyncBreakCheck,
    [Opcode.ProfilePoint]: Opcode.ProfilePoint,
    [Opcode.CreateBaseClass]: Opcode.CreateBaseClass,
    [Opcode.CreateBaseClassLongIndex]: Opcode.CreateBaseClass,
    [Opcode.CreateDerivedClass]: Opcode.CreateDerivedClass,
    [Opcode.CreateDerivedClassLongIndex]: Opcode.CreateDerivedClass,
    [Opcode.CreateClosure]: Opcode.CreateClosure,
    [Opcode.CreateClosureLongIndex]: Opcode.CreateClosure,
    [Opcode.CreateThisForNew]: Opcode.CreateThisForNew,
    [Opcode.CreateThisForSuper]: Opcode.CreateThisForSuper,
    [Opcode.SelectObject]: Opcode.SelectObject,
    [Opcode.LoadParam]: Opcode.LoadParam,
    [Opcode.LoadParamLong]: Opcode.LoadParam,
    [Opcode.LoadConstUInt8]: Opcode.LoadConstUInt8,
    [Opcode.LoadConstInt]: Opcode.LoadConstInt,
    [Opcode.LoadConstDouble]: Opcode.LoadConstDouble,
    [Opcode.LoadConstBigInt]: Opcode.LoadConstBigInt,
    [Opcode.LoadConstBigIntLongIndex]: Opcode.LoadConstBigInt,
    [Opcode.LoadConstString]: Opcode.LoadConstString,
    [Opcode.LoadConstStringLongIndex]: Opcode.LoadConstString,
    [Opcode.LoadConstEmpty]: Opcode.LoadConstEmpty,
    [Opcode.LoadConstUndefined]: Opcode.LoadConstUndefined,
    [Opcode.LoadConstNull]: Opcode.LoadConstNull,
    [Opcode.LoadConstTrue]: Opcode.LoadConstTrue,
    [Opcode.LoadConstFalse]: Opcode.LoadConstFalse,
    [Opcode.LoadConstZero]: Opcode.LoadConstZero,
    [Opcode.CoerceThisNS]: Opcode.CoerceThisNS,
    [Opcode.LoadThisNS]: Opcode.LoadThisNS,
    [Opcode.ToNumber]: Opcode.ToNumber,
    [Opcode.ToNumeric]: Opcode.ToNumeric,
    [Opcode.ToInt32]: Opcode.ToInt32,
    [Opcode.AddEmptyString]: Opcode.AddEmptyString,
    [Opcode.CreatePrivateName]: Opcode.CreatePrivateName,
    [Opcode.GetArgumentsPropByValLoose]: Opcode.GetArgumentsPropByValLoose,
    [Opcode.GetArgumentsPropByValStrict]: Opcode.GetArgumentsPropByValStrict,
    [Opcode.GetArgumentsLength]: Opcode.GetArgumentsLength,
    [Opcode.ReifyArgumentsStrict]: Opcode.ReifyArgumentsStrict,
    [Opcode.ReifyArgumentsLoose]: Opcode.ReifyArgumentsLoose,
    [Opcode.ToPropertyKey]: Opcode.ToPropertyKey,
    [Opcode.CreateRegExp]: Opcode.CreateRegExp,
    [Opcode.UIntSwitchImm]: Opcode.UIntSwitchImm,
    [Opcode.StringSwitchImm]: Opcode.StringSwitchImm,
    [Opcode.CreateGenerator]: Opcode.CreateGenerator,
    [Opcode.CreateGeneratorLongIndex]: Opcode.CreateGenerator,
    [Opcode.IteratorBegin]: Opcode.IteratorBegin,
    [Opcode.IteratorNext]: Opcode.IteratorNext,
    [Opcode.IteratorClose]: Opcode.IteratorClose,
    [Opcode.TypedLoadParent]: Opcode.TypedLoadParent,
    [Opcode.Jmp]: Opcode.Jmp,
    [Opcode.JmpLong]: Opcode.Jmp,
    [Opcode.JmpTrue]: Opcode.JmpTrue,
    [Opcode.JmpTrueLong]: Opcode.JmpTrue,
    [Opcode.JmpFalse]: Opcode.JmpFalse,
    [Opcode.JmpFalseLong]: Opcode.JmpFalse,
    [Opcode.JmpUndefined]: Opcode.JmpUndefined,
    [Opcode.JmpUndefinedLong]: Opcode.JmpUndefined,
    [Opcode.JmpTypeOfIs]: Opcode.JmpTypeOfIs,
    [Opcode.JLess]: Opcode.JLess,
    [Opcode.JLessLong]: Opcode.JLess,
    [Opcode.JNotLess]: Opcode.JNotLess,
    [Opcode.JNotLessLong]: Opcode.JNotLess,
    [Opcode.JLessN]: Opcode.JLessN,
    [Opcode.JLessNLong]: Opcode.JLessN,
    [Opcode.JNotLessN]: Opcode.JNotLessN,
    [Opcode.JNotLessNLong]: Opcode.JNotLessN,
    [Opcode.JLessEqual]: Opcode.JLessEqual,
    [Opcode.JLessEqualLong]: Opcode.JLessEqual,
    [Opcode.JNotLessEqual]: Opcode.JNotLessEqual,
    [Opcode.JNotLessEqualLong]: Opcode.JNotLessEqual,
    [Opcode.JLessEqualN]: Opcode.JLessEqualN,
    [Opcode.JLessEqualNLong]: Opcode.JLessEqualN,
    [Opcode.JNotLessEqualN]: Opcode.JNotLessEqualN,
    [Opcode.JNotLessEqualNLong]: Opcode.JNotLessEqualN,
    [Opcode.JGreater]: Opcode.JGreater,
    [Opcode.JGreaterLong]: Opcode.JGreater,
    [Opcode.JNotGreater]: Opcode.JNotGreater,
    [Opcode.JNotGreaterLong]: Opcode.JNotGreater,
    [Opcode.JGreaterEqual]: Opcode.JGreaterEqual,
    [Opcode.JGreaterEqualLong]: Opcode.JGreaterEqual,
    [Opcode.JNotGreaterEqual]: Opcode.JNotGreaterEqual,
    [Opcode.JNotGreaterEqualLong]: Opcode.JNotGreaterEqual,
    [Opcode.JEqual]: Opcode.JEqual,
    [Opcode.JEqualLong]: Opcode.JEqual,
    [Opcode.JNotEqual]: Opcode.JNotEqual,
    [Opcode.JNotEqualLong]: Opcode.JNotEqual,
    [Opcode.JStrictEqual]: Opcode.JStrictEqual,
    [Opcode.JStrictEqualLong]: Opcode.JStrictEqual,
    [Opcode.JStrictNotEqual]: Opcode.JStrictNotEqual,
    [Opcode.JStrictNotEqualLong]: Opcode.JStrictNotEqual,
    [Opcode.JmpBuiltinIs]: Opcode.JmpBuiltinIs,
    [Opcode.JmpBuiltinIsLong]: Opcode.JmpBuiltinIs,
    [Opcode.JmpBuiltinIsNot]: Opcode.JmpBuiltinIsNot,
    [Opcode.JmpBuiltinIsNotLong]: Opcode.JmpBuiltinIsNot,
};
