import { writeFile } from "fs/promises";

import { entries } from "../utils/index.ts";

// Current React Native version in Discord is v0.86.0. Hermes is referenced here:
// https://github.com/react/react-native/blob/v0.86.0/packages/react-native/package.json#L179
const HERMES_URL = "https://github.com/facebook/hermes/raw/hermes-v250829098.0.14";
const BYTECODE_URL = `${HERMES_URL}/include/hermes/BCGen/HBC/BytecodeList.def`;
const BUILTINS_URL = `${HERMES_URL}/include/hermes/FrontEndDefs/Builtins.def`;

const opcodes = {} as Record<string, string[]>;
const bigIntOps = {} as Record<string, number[]>;
const functionOps = {} as Record<string, number[]>;
const stringOps = {} as Record<string, number[]>;
const builtins = [] as string[];
const longOpcodes = {} as Record<string, string>;
const canonicalOpcodes = {} as Record<string, string>;

parseBytecode(await fetch(BYTECODE_URL).then(res => res.text()));
parseBuiltins(await fetch(BUILTINS_URL).then(res => res.text()));

const src = `\
// auto-generated by genOpcodes.ts

/**
 * Instruction argument types.
 */
export const ArgType = {
    /** Unsigned 8-bit value */
    UInt8: 0,
    /** Unsigned 8-bit register index */
    Reg8: 1,
    /** Signed 8-bit relative address */
    Addr8: 2,
    /** Unsigned 16-bit value */
    UInt16: 3,
    /** Unsigned 32-bit value */
    UInt32: 4,
    /** Unsigned 32-bit register index */
    Reg32: 5,
    /** Signed 32-bit immediate */
    Imm32: 6,
    /** Signed 32-bit relative address */
    Addr32: 7,
    /** Double-precision floating point number */
    Double: 8,
} as const;

export type ArgType = typeof ArgType[keyof typeof ArgType];

/**
 * Numeric Hermes instruction opcodes.
 */
export const Opcode = {
${entries(opcodes).map(([op], index) => `    ${op}: ${index},`).join("\n")}
} as const;

export type Opcode = typeof Opcode[keyof typeof Opcode];

export const opcodeNames = {
${entries(opcodes).map(([op], index) => `    ${index}: "${op}",`).join("\n")}
} as const;

export type OpcodeMap<T> = Readonly<Partial<Record<Opcode, T>>>;

export type OperandSet = OpcodeMap<readonly number[]>;

/**
 * Argument type corresponding to {@link Opcode}.
 */
export const opcodeTypes = {
${entries(opcodes).map(([op, args]) => `    [Opcode.${op}]: [${args.map(a => `ArgType.${a}`).join(", ")}],`).join("\n")}
} as const;

/**
 * Opcodes which have operands referring to the bigint table.
 */
const BIGINT_OPERANDS = {
${entries(bigIntOps).map(([op, args]) => `    [Opcode.${op}]: [${args.join(", ")}],`).join("\n")}
} as const;
export type BigIntOperands = typeof BIGINT_OPERANDS;
export const bigintOperands: OperandSet = BIGINT_OPERANDS;

/**
 * Opcodes which have operands referring to the function table.
 */
const FUNCTION_OPERANDS = {
${entries(functionOps).map(([op, args]) => `    [Opcode.${op}]: [${args.join(", ")}],`).join("\n")}
} as const;
export type FunctionOperands = typeof FUNCTION_OPERANDS;
export const functionOperands: OperandSet = FUNCTION_OPERANDS;

/**
 * Opcodes which have operands referring to the string table.
 */
const STRING_OPERANDS = {
${entries(stringOps).map(([op, args]) => `    [Opcode.${op}]: [${args.join(", ")}],`).join("\n")}
} as const;
export type StringOperands = typeof STRING_OPERANDS;
export const stringOperands: OperandSet = STRING_OPERANDS;

export const Builtin = {
${builtins.map((x, index) => `    "${x}": ${index},`).join("\n")}
} as const;

export type Builtin = typeof Builtin[keyof typeof Builtin];

export const builtinNames = {
${builtins.map((x, index) => `    ${index}: "${x}",`).join("\n")}
};

/**
 * Longer version of opcodes, allowing higher values in their arguments.
 */
export const longOpcodes: OpcodeMap<Opcode> = {
${entries(longOpcodes).map(([short, long]) => `    [Opcode.${short}]: Opcode.${long},`).join("\n")}
};

/**
 * Normalised opcodes without a Short or Long suffix.
 */
export const canonicalOpcodes: Readonly<Record<Opcode, Opcode>> = {
${entries(canonicalOpcodes).map(([opcode, canon]) => `    [Opcode.${opcode}]: Opcode.${canon},`).join("\n")}
};
`;

writeFile("decompiler/src/opcodes.ts", src);

function parseBytecode(listing: string) {
    const OPCODE_RE = /^DEFINE_(\S+)_(\d)\((.*)\)$/gm;
    const OPERAND_RE = /^OPERAND_(\S+)_ID\((.*)\)$/gm;
    const LENGTH_RE = /^(\S*?)(Short|Long(?:Index)?|L|)$/;

    for (const [, dir, count, operands] of listing.matchAll(OPCODE_RE)) {
        const [op, ...args] = operands.split(/, */);

        if (dir == "OPCODE") {
            opcodes[op] = args;
        } else if (dir == "JUMP") {
            const args = Array.from(Array(+count - 1), () => "Reg8");
            opcodes[op] = ["Addr8", ...args];
            opcodes[op + "Long"] = ["Addr32", ...args];
        } else {
            throw Error(`Unknown definition: ${dir}`);
        }
    }

    for (const op of Object.keys(opcodes)) {
        const [, canon, suffix] = op.match(LENGTH_RE)!;

        if (canon in opcodes) {
            if (suffix === "Short") {
                longOpcodes[op] = canon;
            } else if (suffix) {
                longOpcodes[canon] = op;
            }

            canonicalOpcodes[op] = canon;
        } else {
            canonicalOpcodes[op] = op;
        }
    }

    for (const [, dir, operands] of listing.matchAll(OPERAND_RE)) {
        const [name, idx] = operands.split(/, */);

        if (dir == "BIGINT") (bigIntOps[name] ??= []).push(+idx - 1);
        else if (dir == "FUNCTION") (functionOps[name] ??= []).push(+idx - 1);
        else if (dir == "STRING") (stringOps[name] ??= []).push(+idx - 1);
        else throw Error(`Unknown definition: ${dir}`);
    }
}

function parseBuiltins(listing: string) {
    const METHOD_RE = /^BUILTIN_METHOD\((.*)\)$/gm;
    const PRIVATE_RE = /^PRIVATE_BUILTIN\((.*)\)$/gm;

    for (const [, args] of listing.matchAll(METHOD_RE)) {
        const [obj, meth] = args.split(/, */);

        builtins.push(`${obj}.${meth}`);
    }

    for (const [, builtin] of listing.matchAll(PRIVATE_RE)) {
        builtins.push(builtin);
    }
}
